version: "3.7"

services:
    fpm:
        build:
            context: ./docker
            dockerfile: Dockerfile-php
        environment:
            - DATABASE_URL= ${DATABASE_URL}
        volumes:
            - ./:/var/www/project/:cached
        networks:
            - symfony
    nginx:
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        volumes:
            - ./:/var/www/project/:cached
        ports:
            - 8000:80
        networks:
            - symfony
    database:

        image: postgres:15-alpine
        platform: linux/x86_64
        volumes:
            - persistent:/var/lib/pgsql
        environment:
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        ports:
            - 5432:5432
        networks:
            - symfony

networks:
    symfony:


volumes:
    persistent:
