version: "3.7"

services:
  fpm:
    build:
      # Info to build the Docker image
      context: ./docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    environment:
      # You can use this section to set environment variables. But you can also use the .env file.
      - DATABASE_URL= ${DATABASE_URL}
    volumes:
      - ./:/var/www/project/:cached # Location of the project for php-fpm. Note this should be the same for NGINX.*
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 10302:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
      - symfony
  database:
    
    
      image: postgres:15-alpine
      platform: linux/x86_64
      volumes:
        - persistent:/var/lib/pgsql
      environment:
        POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      ports:
        - 5432:5432
      networks:
        - symfony

networks:
  symfony:


volumes:
  persistent:
